### ISSUE TITLE
Show your landing page URL in your Repository About Section

### ISSUE THREAD

**Issue by yilverdeja** [TakExplores/first-landing-page#1]
Hey!

Can you add your landing page URL (https://takexplores.github.io/first-landing-page/) to your repositories `About` section. It would be very helpful to view what you created for passerby's like me!

If you don't know how to change the `About` information, take a look at this [StackOverflow Response](https://stackoverflow.com/a/62767178).

Cheers!

**Comment by takbuilds** [comment]
Done! Thanks for the tip @yilverdeja. Obviously still in the very amateur phases but I'll get there :) 

Feel free to suggest anything. If you think something in my code/design is shitty just put it bluntly, I don't mind at all.
